swagger: '2.0'
security:
  - api_key: []
info:
  description: This is a API for stock trading revenue calculator
  version: 1.0.0
  title: revenuecalculatorservice Revenue Calculator Service
  contact:
    email: revathi.thangavel@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
produces:
- application/json
x-google-backend:
  address: https://revenuecalculatorservice-l7o4jvnara-km.a.run.app
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
tags:
- name: customer
  description: Secured customer calls

paths:
  /calculateRevenue:
   
    post:
      tags:
      - customer
      summary: Sending json data to calculate revenue
      operationId: revenueCalculation
      description:  By passing in the appropriate options, you can calculate revenue for the years
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: calculateRevenue
        description: calculate revenue based on the user input
        schema:
          $ref: '#/definitions/customerInput'
      responses:
        200:
          description: revenue calculated
          schema:
            type: array
            items:
              $ref: '#/definitions/Revenue'
        400:
          description: invalid input, object invalid
        
definitions:
  Revenue:
    type: object
    properties:
      Year:
        type: string
        example: 2018-2019
      Items:
       type: array
       items:
         $ref: '#/definitions/SoldSharesRevenue'
    
  SoldSharesRevenue:
    type: object
    properties:
      Date:
        type: string
        format: date-time
        example: '2016-08-29T09:12:33.001Z'
      Market:
        type: string
        example: NEXTDC Ltd
      Quantity:
        type: integer
        example: 399
      PandL:
        type: number
        example: 400.23
      SellUnitPrice:
        type: number
        example: 1.9
  customerInput:
    type: object
    required:
    - TransactionData
    properties:
      FinancialYear:
        type: string
        example: 2021
      StartFinancialMonth:
        type: string
        example: June
      EndFinancialMonth:
        type: string
        example: July
      SkipCorporateAction:
        type: boolean
        example: true
        
      TransactionData:
        $ref: '#/definitions/transactionData'
        
  transactionData:
    required:
    - Date
    - Market
    - Cost
    - Direction
    - Price
    - Activity
    - Quantity
    properties:
      Date:
        type: string
        format: date-time
        example: '2016-08-29T09:12:33.001Z'
      Market:
        type: string
        example:  NextTDC Ltd
      Cost:
        type: number
        example: 408
      Direction:
        type: string
        example: SELL
      Price:
        type: number
        example: 6.25
      Activity:
        type: string
        example: TRADE
      Quantity:
        type: integer
        example: 500
        
# Added by API Auto Mocking Plugin
# host: localhost
#basePath: /traderevenuecalc/revenueCalculator/1.0.0
schemes:
 - https
# Added by API Auto Mocking Plugin
# host: localhost
# Added by API Auto Mocking Plugin
#host: virtserver.swaggerhub.com